server:
  port: 8080


eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true 
  instance: 
    status-page-url-path:  ${management.contextPath}/info
    health-check-url-path: ${management.contextPath}/health
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp 

