server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: eureka
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:8761/
  server: 
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: true
